# Generated by Django 3.1.7 on 2021-03-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210303_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsegment',
            name='title',
            field=models.TextField(),
        ),
    ]
