# Generated by Django 3.1.7 on 2021-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20210303_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='exersises',
        ),
        migrations.AddField(
            model_name='lesson',
            name='motivation',
            field=models.TextField(default='motivation is here'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reflection',
            field=models.TextField(default='reflection is here'),
        ),
        migrations.AddField(
            model_name='lessonsegment',
            name='skill',
            field=models.TextField(blank=True),
        ),
    ]
