# Generated by Django 3.1.7 on 2021-04-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20210425_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='thematic_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessonsegment')),
            ],
        ),
    ]
