# Generated by Django 3.1.7 on 2021-04-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_thematic_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='thematic_plan',
            new_name='ThematicPlan',
        ),
    ]
