# Generated by Django 3.1.7 on 2021-05-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_auto_20210425_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsegment',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_set', to='lessons.lesson'),
        ),
        migrations.DeleteModel(
            name='ThematicPlan',
        ),
    ]
